name: publish
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8.7.6

      - name: Install deps
        run: pnpm install

      - name: Build
        run: pnpm build --filter=tailwind

      # for npm README
      - name: Copy README
        run: cp -f README.md packages/tailwind/README.md

      - name: Publish
        # --no-git-checks for "Copy README" step `Unclean working tree` problem
        run: pnpm publish --access public --no-git-checks --filter=@sira-ui/tailwind
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}