name: Publish to NPM
on:
  release:
    types: [ created ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7.17.1

      - name: Install deps
        run: pnpm install

      - name: Build
        run: pnpm run build --filter=@sira-ui/tailwind

      - name: Publish package on NPM 📦
        run: pnpm publish --access public --filter=@sira-ui/tailwind
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
